---
- name: "config secret {{ name }}"
  include: "secret.yml"

- name: "deploy service {{ name }}"
  block:
  - name: "deploy serv {{ name }}"
    community.docker.docker_swarm_service:
      name: "{{ name }}"
      image: rabbitmq:3-management
      state: present
      networks: "{{ network_name }}"
      
      
  tags: "{{ name }}"     
