---
# - name: pause
#   pause:
#     minutes: 3
    
- name: "deploy services{{ name }}"
  block:
  - name: "deploy service {{ name }}"
    community.docker.docker_swarm_service:
      name: "{{ name }}"
      image: "rabbitmq:{{ version }}"
      state: present
      networks: "{{ network_name }}"
      env:
        - RABBITMQ_DEFAULT_USER={{ rmq.user }}
        - RABBITMQ_DEFAULT_PASS={{ rmq.password }}
  tags: "{{ name }}"     
