---
- name: deploy task
  command: "echo {{ test }}"
  register: result
  changed_when: "'0' not in result.stdout"

- name: debug
  debug:
    var: result
  # verbosity: 5

- name: cycle
  vars:
    data:
      a: 1
      b: 2
  debug:
    msg: "{{ item.key }} = {{ item.value }}"
    #msg: "{{ item.name }} is {{ item.group }}"
  loop: "{{ data | dict2items }}"
    #- {name: "Ars", group: "Admin"}
    #- {name: "Ars", group: "DevOps"}
    
- name: register
  command: echo "{{ item }}"
  loop: 
  - a
  - b
  register: res

- name: debug
  debug:
    var: res

- name: iteration on dict
  debug:
    var: "{{ item }}"
  loop: "{{ groups['all'] }}"


      