---
- name: Create a network with driver options
  community.docker.docker_network:
    # name: "{{ network_name }}"
    name: network
    driver: overlay

- name: upload services
  include: "../services/{{ item.name }}/service.yml"
  vars:
    - name: "{{ item.name }}"
    - version: "{{ item.version }}"
  loop: "{{ services }}"
