---
- name: deploy task
  command: "echo {{ test }}"
  register: result
  changed_when: "'0' not in result.stdout"

- name: debug
  debug:
    var: result
  # verbosity: 5

- name: cycle
  vars:
    data:
      a: 1
      b: 2
  debug:
    msg: "{{ item.key }} = {{ item.value }}"
    #msg: "{{ item.name }} is {{ item.group }}"
  loop: "{{ data | dict2items }}"
    #- {name: "Ars", group: "Admin"}
    #- {name: "Ars", group: "DevOps"}
    
- name: register
  command: echo "{{ item }}"
  loop: 
  - a
  - b
  register: res

- name: debug
  debug:
    var: res

- name: iteration of inventory
  debug:
    msg: "{{ item }}"
  loop: "{{ groups['all'] }}"

- name: big object
  debug:
    msg: "{{ item.name }} - {{ index }} - {{ ansible_loop.allitems }}"
  loop:
    - name: Ars
      group: "Admin"
      roles:
        admin: true
        manager: true
        user: true
    - name: alex
    - name: alex2
  loop_control:
    label: "{{ item.name }}"
    pause: 3
    index_var: index
    extended: yes

- name: loop_var
  debug:
    msg: "{{ outer_item.name }}"
  loop:
    - name: Ars
    - name: Van
    - name: Kim
  loop_control:
    loop_var: outer_item

- name: loop_var
  include_tasks: inner.yml
  loop:
    - name: Ars
    - name: Van
    - name: Kim
  loop_control:
    loop_var: outer_item

