---
- name: deploy task
  command: "echo {{ test }}"
  register: result
  changed_when: "'0' in result.stdout"

- name: debug
  debug:
    var: result
    verbosity: 5

- name: cikle
  debug:
    msg: "{{ item }}"
  loop:
    - a
    - b
