---
- name: deploy task
  command: "echo {{ test }}"
  register: result
  changed_when: "'0' not in result.stdout"

- name: debug
  debug:
    var: result
  # verbosity: 5

- name: cycle
  vars:
    data:
      a: 1
      b: 2
  debug:
    msg: "{{ item.key }} = {{ item.value }}"
    #msg: "{{ item.name }} is {{ item.group }}"
  loop: "{{ data | dict2items }}"
    #- {name: "Ars", group: "Admin"}
    #- {name: "Ars", group: "DevOps"}
    
- name: register
  command: echo "{{ item }}"
  loop: 
  - a
  - b
  register: res

- name: debug
  debug:
    var: res

- name: iteration of inventory
  debug:
    msg: "{{ item }}"
  loop: "{{ groups['all'] }}"

- name: big object
  debug:
    msg: "{{ item.name }} - {{ index }} - {{ ansible_loop.allitems }}"
  loop:
    - name: Ars
      group: "Admin"
      roles:
        admin: true
        manager: true
        user: true
    - name: alex
    - name: alex2
  loop_control:
    label: "{{ item.name }}"
    pause: 3
    index_var: index
    extended: yes

- name: loop_var
  debug:
    msg: "{{ outer_item.name }}"
  loop:
    - name: Ars
    - name: Van
    - name: Kim
  loop_control:
    loop_var: outer_item

- name: loop_var
  include_tasks: inner.yml
  loop:
    - name: Ars
    - name: Van
    - name: Kim
  loop_control:
    loop_var: outer_item

- name: file
  debug:
    msg: "{{ lookup('file', 'main.yml', errors='warn') }}"

- name: vars
  vars:
    name: a
  debug:
    msg: "{{ lookup('vars', 'name') }}"

- name: filters
  debug:
    msg: "{{ my_var | default(5)}}"

- name: file
  ignore_errors: true
  file:
    dest: "{{ item.path }}"
    state: touch
    mode: "{{ item.mode | default(omit) }}"
  loop:
    - path: "/test"
    - path: "../test_2"
      mode: "0666"

- name: vars admin_true
  vars:
    admin: true
  debug:
    msg: "{{ admin | type_debug }}"

- name: item to dict
  vars:
    admin:
      - key: a
        value: 1
      - key: b
        value: 2
  debug:
    msg: "{{ admin | items2dict }}"
      
- name: item to dict another number of keys_values
  vars:
    admin:
      - keys: a
        values: 1
      - keys: b
        values: 2
  debug:
    msg: "{{ admin | items2dict(key_name='keys', value_name='values') }}"
  
