---
- name: Create a network with driver options
  community.docker.docker_network:
    name: network_two
    driver: overlay

- name: upload services
  include: "..services/{{ item }}/service.yml"
  vars:
    name: "{{ item }}"
  loop: "{{ services }}"
