---
- name: deploys server
  hosts: deploy
  roles:
#    - role: deploy
#      message: "mes1"
#    - role: deploy
#      message: "mes2"  
    - role: preconfig
#    - role: deploy
#    - role:swarm_init
    
- name: manager
  hosts: managers
  roles: 
    - preconfig
#    - swarm_join

- name: workers
  hosts: workers
  roles: 
    - preconfig
#    - swarm_join
