---
- name: deploys server
  hosts: deploy
  roles:
#    - role: deploy
#      message: "mes1"
#    - role: deploy
#      message: "mes2"  
    - role: preconfig
      tags: preconfig
    - role: deploy
    #  test: 0
      tags: deploy
#    - role: deploy
#    - role:swarm_init
    
- name: manager
  hosts: managers
  roles: 
    - role:  preconfig
      tags: preconfig
#    - swarm_join

- name: workers
  hosts: workers
  roles: 
    - role: preconfig
      tags: preconfig
#    - swarm_join
