---
- name: deploy  / build server
  hosts: deploy
  roles:

  - role: preconfig
    tags: preconfig
  - role: build
    tags: build
  - role: deploy
    tags: deploy
  - role: swarm_init
    tags: swarm_init
# - role:swarm_init
# test: 0  
#    - role: deploy

#    - role: deploy
#      message: "mes1"
#    - role: deploy
#      message: "mes2"  
    
- name: Manager
  hosts: managers
  roles: 
    - role: preconfig
      tags: preconfig
    - role: swarm_join
      type: manager
      tags: swarm_join
#    - swarm_join

- name: Worker
  hosts: workers
  roles: 
    - role: preconfig
      tags: preconfig
    - role: swarm_join
      type: worker
      tags: swarm_join
      
  post_tasks: 
  - name: clear tokens folder
    file:
      path: ./tokens
      state: absent
    ignore_errors: true
    delegate_to: localhost
    tags: swarm_join