---
- name: deploy  / build server
  hosts: deploy
  roles:

  - role: preconfig
    tags: preconfig
  - role: build
    tags: build
  - role: deploy
    tags: deploy
  - tags: registry
    role: registry
    
# - role:swarm_init
# test: 0  
#    - role: deploy

#    - role: deploy
#      message: "mes1"
#    - role: deploy
#      message: "mes2"  
    
- name: manager
  hosts: managers
  roles: 
    - role: preconfig
      tags: preconfig
#    - swarm_join

- name: workers
  hosts: workers
  roles: 
    - role: preconfig
      tags: preconfig
#    - swarm_join
