---
# - name: connecting
#   debug:
#     msg: "{{ hostvars['test_server1']['ansible_facts']['docker_gwbridge']['ipv4']['address'] }}"


- name: connecting
  vars:
    token: "{{ lookup('file', '../../tokens/token-{{ type }}') }}"
  community.docker.docker_swarm:
    state: join
    remote_addrs: "{{ advertise_addr }}"
    join_token: > 
      "{{
      hostvars['test_server1']['ansible_facts']['token_worker'] 
      if type== 'worker' 
        else
      hostvars['test_server1']['ansible_facts']['token_manager'] 
      }}"
    