---
- name: "config secret {{ name }}"
  block:
  - name: "Create secret {{ name }}"
    include: "../secret-create.yml"
  tags: "{{ name }}"

  rescue:
    - name: "{{ name }} del service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent

    - name: "Create secret {{ name }}"
      include: "../secret-create.yml"
        