---
- name: "config secret {{ name }}"
  block:
  - name: "Create secret {{ name }}"
    community.docker.docker_secret:
      name: "{{ name }}.env"
      data: "{{ lookup('file', '.env') | b64encode }}"
      labels:
        secret: "{{ lookup('file', '.env') | hash('sha1') }}"
      data_is_b64: true
      state: present
  
  rescue:
    - name: "{{ name }} del service"
      community.docker.docker_swarm_service:
        name: "{{ name }}"
        state: absent
    - name: "Create secret {{ name }}"
      community.docker.docker_secret:
        name: "{{ name }}.env"
        data: "{{ lookup('file', '.env') | b64encode }}"
        labels:
          secret: "{{ lookup('file', '.env') | hash('sha1') }}"
        data_is_b64: true
        state: present        

- name: "deploy service {{ name }}"
  block:
  - name: "deploy service {{ name }}"
    community.docker.docker_swarm_service:
      name: "{{ name }}"
      image: localhost:5000/api:latest
      state: present
      networks: "{{ networkName }}"
      publish:
          mode: ingress
          protcol: tcp
          published_port: 3002
          target_port: 3000
      secrets:
          - secret_name: "{{ name }}.env"
            filename: "/opt/app/.env"
        
