---
- name: "config secret {{ name }}"
  include: "secret.yml"

- name: "deploy service {{ name }}"
  block:
  - name: "deploy serv {{ name }}"
    community.docker.docker_swarm_service:
      name: "{{ name }}"
      image: localhost:5000/{{ name }}:latest
      state: present
      networks: "{{ networkName }}"
      publish:
        - mode: ingress
          protocol: tcp
          published_port: 3002
          target_port: 3000
      secrets:
          - secret_name: "{{ name }}.env"
            filename: "/opt/app/.env"
  tags: "{{ name }}"     
