---
- name: "config secret {{ name }}"
  include: "secret.yml"

- name: "deploy services {{ name }}"
  block:
  - name: "deploy service {{ name }}"
    community.docker.docker_swarm_service:
      name: "{{ name }}"
      image: "{{ registry_name }}{{ name }}:{{ version }}"
      state: present
      networks:
        - name: "{{ network_name }}"
      publish:
        - mode: ingress
          protocol: tcp
          published_port: 3002
          target_port: 3000
      secrets:
          - secret_name: "{{ name }}.env"
            filename: "/opt/app/.env"
  tags: "{{ name }}"     
