---
- name: "config configs {{ name }}"
  include: "../config.yml"
  loop:
    - nginx.conf
  loop_control:
    loop_var: config_item


- name: "deploy services {{ name }}"
  block:
  - name: "deploy service {{ name }}"
    community.docker.docker_swarm_service:
      name: "{{ name }}"
      image: "nginx:{{ version }}"
      state: present
      networks: "{{ network_name }}"
      publish:
        - mode: "{{ mode_pub }}"
          protocol: tcp
          published_port: 80
          target_port: 80
      configs:
        - config_name: nginx.conf
          filename: "/etc/nginx/nginx.conf"
  tags: "{{ name }}"
