---
- name: "config configs {{ name }}"
  include: "../config.yml"
  loop:
    - nginx.conf
  loop_control:
    loop_var: config_item


- name: "deploy services {{ name }}"
  block:
  - name: "deploy service {{ name }}"
    community.docker.docker_swarm_service:
      name: "{{ name }}"
      image: "{{ registry_name }}{{ name }}:{{ version }}"
      state: present
      force_update: true
      networks: "{{ network_name }}"
      publish:
        - mode: ingress
          protocol: tcp
          published_port: 3002
          target_port: 3000
  tags: "{{ name }}"
