---
- name: registry
  block:
  - name: "create {{ name }}"
    community.docker.docker_swarm_service:
      name: "{{ name }}"
      image: "{{ registry_name }}{{ name }}:{{ version }}"
      state: present
      networks: "{{ network_name }}"
      publish:
      - mode: ingress
        protokol: tcp
        published_port: 5000
        target_port: 5000
      mounts:
        source:/home/vagrant/registry
        target://var/lib/registry
  tags: "{{ name }}"   