---
- name: init_swarm
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ advertise_addr }}"
  register: token

- name: save tokens
  ansible.builtin.set_fact:
    debug: yes
    token_manager: "{{ token.swarm_facts.JoinTokens.Manager }}"
    token_worker: "{{ token.swarm_facts.JoinTokens.Worker }}"
    cacheable: yes

####### if used local machine ######
# - name: directory is present
#   local_action:
#     module: file
#     path: ./tokens
#     state: directory
####################################

# - name: directory is present
#   file:
#     path: ./tokens
#     state: directory
#     mode: 0755
#   delegate_to: localhost
#   notify: exam with folder is create

# - name: save token for manager
#   copy:
#     dest: ./tokens/token-manager
#     content: "{{ token.swarm_facts.JoinTokens.Manager }}"
#     mode: 0644
#   delegate_to: localhost

# - name: save token for worker
#   copy:
#     dest: ./tokens/token-worker
#     content: "{{ token.swarm_facts.JoinTokens.Worker }}"
#     mode: 0644
#   delegate_to: localhost


# if used hosts machine
# - name: directory is present
#   file:
#     path: ./tokens
#     state: directory