---
- name: init swarm
  community.docker.docker_swarm:
    state: present
    advertise_addr: 10.11.10.1
  register: token

- name: directory is present
  local_action:
    module: file
    path: ./tokens
    state: directory

- name: save token for manager
  local_action:
    module: copy
    dest: ./tokens/token-manager
    content: "{{ token.swarm_facts.JoinTokens.Manager }}"

- name: save token for worker
  local_action:
    module: copy
    dest: ./tokens/token-worker
    content: "{{ token.swarm_facts.JoinTokens.Worker }}"

# if used hosts machine
# - name: directory is present
#   file:
#     path: ./tokens
#     state: directory