---
- name: "deploy services {{ name }}"
  block:
  - name: "deploy service {{ name }}"
    community.docker.docker_swarm_service:
      name: "{{ name }}"
      image: "{{ registry_name }}{{ name }}:{{ version }}"
      state: present
      networks: "{{ network_name }}"
      publish:
        - mode: host
          protocol: tcp
          published_port: 3001
          target_port: 80
  tags: "{{ name }}"     
