- name: "Create secret {{ name }}"
  community.docker.docker_secret:
    name: "{{ name }}.env"
    data: "{{ lookup('file', '{{ name }}/.env') | b64encode }}"
    labels:
      secret: "{{ lookup('file', '.env') | hash('sha1') }}"
    data_is_b64: true
    state: present
